eventMapping:
  - eventName: demand
    sourceSysVersion: ''
    iFixVersion: ''
    mappings:
      - name: 'projectId'
        path: ''
        type: ''
        value: ''
      - name: 'eventTime'
        path: ''
        type: ''
        value: ''

  - eventName: collection
    sourceSysVersion: ''
    iFixVersion: ''
    mappings:
      - name: ''
        path: ''
        type: ''
        value: ''
      - name: ''
        path: ''
        type: ''
        value: ''