CREATE INDEX IF NOT EXISTS index_eg_ifix_chartofaccount_id ON eg_ifix_chartofaccount(id);
CREATE INDEX IF NOT EXISTS index_eg_ifix_chartofaccount_tenantid ON eg_ifix_chartofaccount(tenantid);
CREATE INDEX IF NOT EXISTS index_eg_ifix_chartofaccount_majorhead ON eg_ifix_chartofaccount(majorhead);
CREATE INDEX IF NOT EXISTS index_eg_ifix_chartofaccount_submajorhead ON eg_ifix_chartofaccount(submajorhead);
CREATE INDEX IF NOT EXISTS index_eg_ifix_chartofaccount_minorhead ON eg_ifix_chartofaccount(minorhead);
CREATE INDEX IF NOT EXISTS index_eg_ifix_chartofaccount_subhead ON eg_ifix_chartofaccount(subhead);
CREATE INDEX IF NOT EXISTS index_eg_ifix_chartofaccount_grouphead ON eg_ifix_chartofaccount(grouphead);
CREATE INDEX IF NOT EXISTS index_eg_ifix_chartofaccount_objecthead ON eg_ifix_chartofaccount(objecthead);
CREATE INDEX IF NOT EXISTS index_eg_ifix_chartofaccount_coacode ON eg_ifix_chartofaccount(coacode);
