DROP TABLE IF EXISTS fiscal_event_aggregated;

CREATE TABLE fiscal_event_aggregated(
  ver TEXT,
  id SERIAL,

  sumAmount DECIMAL,
  count bigint,
  fiscalPeriod TEXT,

  type TEXT,

  attributes_project_id TEXT,

  tenantId TEXT,
  government_id TEXT,
  government_name TEXT,
  attributes_department_id  TEXT,
  attributes_department_code TEXT,
  attributes_department_name TEXT,
  attributes_departmentEntity_code TEXT,
  attributes_departmentEntity_hierarchyLevel integer,
  attributes_departmentEntity_id TEXT,
  attributes_departmentEntity_name TEXT,
  attributes_departmentEntity_ancestry_0_id TEXT,
  attributes_departmentEntity_ancestry_0_code TEXT,
  attributes_departmentEntity_ancestry_0_name TEXT,
  attributes_departmentEntity_ancestry_0_hierarchyLevel integer,
  attributes_departmentEntity_ancestry_1_id TEXT,
  attributes_departmentEntity_ancestry_1_code TEXT,
  attributes_departmentEntity_ancestry_1_name TEXT,
  attributes_departmentEntity_ancestry_1_hierarchyLevel integer,
  attributes_departmentEntity_ancestry_2_id TEXT,
  attributes_departmentEntity_ancestry_2_code TEXT,
  attributes_departmentEntity_ancestry_2_name TEXT,
  attributes_departmentEntity_ancestry_2_hierarchyLevel integer,
  attributes_departmentEntity_ancestry_3_id TEXT,
  attributes_departmentEntity_ancestry_3_code TEXT,
  attributes_departmentEntity_ancestry_3_name TEXT,
  attributes_departmentEntity_ancestry_3_hierarchyLevel integer,
  attributes_departmentEntity_ancestry_4_id TEXT,
  attributes_departmentEntity_ancestry_4_code TEXT,
  attributes_departmentEntity_ancestry_4_name TEXT,
  attributes_departmentEntity_ancestry_4_hierarchyLevel integer,
  attributes_departmentEntity_ancestry_5_id TEXT,
  attributes_departmentEntity_ancestry_5_code TEXT,
  attributes_departmentEntity_ancestry_5_name TEXT,
  attributes_departmentEntity_ancestry_5_hierarchyLevel integer,
  attributes_departmentEntity_ancestry_6_id TEXT,
  attributes_departmentEntity_ancestry_6_code TEXT,
  attributes_departmentEntity_ancestry_6_name TEXT,
  attributes_departmentEntity_ancestry_6_hierarchyLevel integer,
  attributes_departmentEntity_ancestry_7_id TEXT,
  attributes_departmentEntity_ancestry_7_code TEXT,
  attributes_departmentEntity_ancestry_7_name TEXT,
  attributes_departmentEntity_ancestry_7_hierarchyLevel integer,
  attributes_departmentEntity_ancestry_8_id TEXT,
  attributes_departmentEntity_ancestry_8_code TEXT,
  attributes_departmentEntity_ancestry_8_name TEXT,
  attributes_departmentEntity_ancestry_8_hierarchyLevel integer,
  attributes_departmentEntity_ancestry_9_id TEXT,
  attributes_departmentEntity_ancestry_9_code TEXT,
  attributes_departmentEntity_ancestry_9_name TEXT,
  attributes_departmentEntity_ancestry_9_hierarchyLevel integer,
  attributes_departmentEntity_ancestry_10_id TEXT,
  attributes_departmentEntity_ancestry_10_code TEXT,
  attributes_departmentEntity_ancestry_10_name TEXT,
  attributes_departmentEntity_ancestry_10_hierarchyLevel integer,
  attributes_expenditure_id TEXT,
  attributes_expenditure_code TEXT,
  attributes_expenditure_name TEXT,
  attributes_expenditure_type TEXT,
  attributes_project_code TEXT,
  attributes_project_name TEXT,

  coa_id TEXT,
  coa_coaCode TEXT,
  coa_majorHead TEXT,
  coa_majorHeadName TEXT,
  coa_majorHeadType TEXT,
  coa_subMajorHead TEXT,
  coa_subMajorHeadName TEXT,
  coa_minorHead TEXT,
  coa_minorHeadName TEXT,
  coa_subHead TEXT,
  coa_subHeadName TEXT,
  coa_groupHead TEXT,
  coa_groupHeadName TEXT,
  coa_objectHead TEXT,
  coa_objectHeadName TEXT,

  unique(attributes_project_id,coa_id,fiscalPeriod,type),
  PRIMARY KEY (id)
);
