ALTER TABLE fiscal_event_aggregated RENAME department_id TO attributes_department_id;
ALTER TABLE fiscal_event_aggregated RENAME department_code TO attributes_department_code;
ALTER TABLE fiscal_event_aggregated RENAME department_name TO attributes_department_name;

ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_code TO attributes_departmentEntity_code;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_hierarchyLevel TO attributes_departmentEntity_hierarchyLevel;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_id TO attributes_departmentEntity_id;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_name TO attributes_departmentEntity_name;

ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_0_id TO attributes_departmentEntity_ancestry_0_id;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_0_code TO attributes_departmentEntity_ancestry_0_code;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_0_name TO attributes_departmentEntity_ancestry_0_name;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_0_hierarchyLevel TO attributes_departmentEntity_ancestry_0_hierarchyLevel;

ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_1_id TO attributes_departmentEntity_ancestry_1_id;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_1_code TO attributes_departmentEntity_ancestry_1_code;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_1_name TO attributes_departmentEntity_ancestry_1_name;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_1_hierarchyLevel TO attributes_departmentEntity_ancestry_1_hierarchyLevel;

ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_2_id TO attributes_departmentEntity_ancestry_2_id;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_2_code TO attributes_departmentEntity_ancestry_2_code;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_2_name TO attributes_departmentEntity_ancestry_2_name;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_2_hierarchyLevel TO attributes_departmentEntity_ancestry_2_hierarchyLevel;


ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_3_id TO attributes_departmentEntity_ancestry_3_id;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_3_code TO attributes_departmentEntity_ancestry_3_code;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_3_name TO attributes_departmentEntity_ancestry_3_name;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_3_hierarchyLevel TO attributes_departmentEntity_ancestry_3_hierarchyLevel;

ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_4_id TO attributes_departmentEntity_ancestry_4_id;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_4_code TO attributes_departmentEntity_ancestry_4_code;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_4_name TO attributes_departmentEntity_ancestry_4_name;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_4_hierarchyLevel TO attributes_departmentEntity_ancestry_4_hierarchyLevel;

ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_5_id TO attributes_departmentEntity_ancestry_5_id;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_5_code TO attributes_departmentEntity_ancestry_5_code;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_5_name TO attributes_departmentEntity_ancestry_5_name;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_5_hierarchyLevel TO attributes_departmentEntity_ancestry_5_hierarchyLevel;

ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_6_id TO attributes_departmentEntity_ancestry_6_id;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_6_code TO attributes_departmentEntity_ancestry_6_code;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_6_name TO attributes_departmentEntity_ancestry_6_name;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_6_hierarchyLevel TO attributes_departmentEntity_ancestry_6_hierarchyLevel;

ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_7_id TO attributes_departmentEntity_ancestry_7_id;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_7_code TO attributes_departmentEntity_ancestry_7_code;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_7_name TO attributes_departmentEntity_ancestry_7_name;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_7_hierarchyLevel TO attributes_departmentEntity_ancestry_7_hierarchyLevel;

ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_8_id TO attributes_departmentEntity_ancestry_8_id;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_8_code TO attributes_departmentEntity_ancestry_8_code;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_8_name TO attributes_departmentEntity_ancestry_8_name;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_8_hierarchyLevel TO attributes_departmentEntity_ancestry_8_hierarchyLevel;

ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_9_id TO attributes_departmentEntity_ancestry_9_id;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_9_code TO attributes_departmentEntity_ancestry_9_code;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_9_name TO attributes_departmentEntity_ancestry_9_name;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_9_hierarchyLevel TO attributes_departmentEntity_ancestry_9_hierarchyLevel;

ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_10_id TO attributes_departmentEntity_ancestry_10_id;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_10_code TO attributes_departmentEntity_ancestry_10_code;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_10_name TO attributes_departmentEntity_ancestry_10_name;
ALTER TABLE fiscal_event_aggregated RENAME departmentEntity_ancestry_10_hierarchyLevel TO attributes_departmentEntity_ancestry_10_hierarchyLevel;


ALTER TABLE fiscal_event_aggregated RENAME expenditure_id TO attributes_expenditure_id;
ALTER TABLE fiscal_event_aggregated RENAME expenditure_code TO attributes_expenditure_code;
ALTER TABLE fiscal_event_aggregated RENAME expenditure_name TO attributes_expenditure_name;
ALTER TABLE fiscal_event_aggregated RENAME expenditure_type TO attributes_expenditure_type;

ALTER TABLE fiscal_event_aggregated RENAME project_code TO attributes_project_code;
ALTER TABLE fiscal_event_aggregated RENAME project_name TO attributes_project_name;
ALTER TABLE fiscal_event_aggregated RENAME project_id TO attributes_project_id;

ALTER TABLE fiscal_event_aggregated DROP CONSTRAINT IF EXISTS fiscal_event_aggregated_project_id_coa_id_fiscalperiod_type_key;
ALTER TABLE fiscal_event_aggregated ADD CONSTRAINT attributes_departmentEntity_ancestry_6_id_coa_id_fiscalPeriod_type_key UNIQUE (attributes_departmentEntity_ancestry_6_id,coa_id,fiscalPeriod,type);
