CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_sumAmount ON fiscal_event_aggregated (sumAmount);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_count ON fiscal_event_aggregated (count);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_fiscalPeriod ON fiscal_event_aggregated (fiscalPeriod);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_type ON fiscal_event_aggregated (type);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_tenantId ON fiscal_event_aggregated (tenantId);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_government_id ON fiscal_event_aggregated (government_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_government_name ON fiscal_event_aggregated (government_name);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_department_id ON fiscal_event_aggregated (department_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_department_code ON fiscal_event_aggregated (department_code);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_department_name ON fiscal_event_aggregated (department_name);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_code ON fiscal_event_aggregated (departmentEntity_code);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_hierarchyLevel ON fiscal_event_aggregated (departmentEntity_hierarchyLevel);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_id ON fiscal_event_aggregated (departmentEntity_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_name ON fiscal_event_aggregated (departmentEntity_name);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_0_id ON fiscal_event_aggregated (departmentEntity_ancestry_0_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_0_code ON fiscal_event_aggregated (departmentEntity_ancestry_0_code);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_0_name ON fiscal_event_aggregated (departmentEntity_ancestry_0_name);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_0_hierarchyLevel ON fiscal_event_aggregated (departmentEntity_ancestry_0_hierarchyLevel);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_1_id ON fiscal_event_aggregated (departmentEntity_ancestry_1_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_1_code ON fiscal_event_aggregated (departmentEntity_ancestry_1_code);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_1_name ON fiscal_event_aggregated (departmentEntity_ancestry_1_name);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_1_hierarchyLevel ON fiscal_event_aggregated (departmentEntity_ancestry_1_hierarchyLevel);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_2_id ON fiscal_event_aggregated (departmentEntity_ancestry_2_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_2_code ON fiscal_event_aggregated (departmentEntity_ancestry_2_code);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_2_name ON fiscal_event_aggregated (departmentEntity_ancestry_2_name);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_2_hierarchyLevel ON fiscal_event_aggregated (departmentEntity_ancestry_2_hierarchyLevel);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_3_id ON fiscal_event_aggregated (departmentEntity_ancestry_3_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_3_code ON fiscal_event_aggregated (departmentEntity_ancestry_3_code);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_3_name ON fiscal_event_aggregated (departmentEntity_ancestry_3_name);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_3_hierarchyLevel ON fiscal_event_aggregated (departmentEntity_ancestry_3_hierarchyLevel);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_4_id ON fiscal_event_aggregated (departmentEntity_ancestry_4_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_4_code ON fiscal_event_aggregated (departmentEntity_ancestry_4_code);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_4_name ON fiscal_event_aggregated (departmentEntity_ancestry_4_name);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_4_hierarchyLevel ON fiscal_event_aggregated (departmentEntity_ancestry_4_hierarchyLevel);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_5_id ON fiscal_event_aggregated (departmentEntity_ancestry_5_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_5_code ON fiscal_event_aggregated (departmentEntity_ancestry_5_code);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_5_name ON fiscal_event_aggregated (departmentEntity_ancestry_5_name);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_5_hierarchyLevel ON fiscal_event_aggregated (departmentEntity_ancestry_5_hierarchyLevel);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_6_id ON fiscal_event_aggregated (departmentEntity_ancestry_6_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_6_code ON fiscal_event_aggregated (departmentEntity_ancestry_6_code);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_6_name ON fiscal_event_aggregated (departmentEntity_ancestry_6_name);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_6_hierarchyLevel ON fiscal_event_aggregated (departmentEntity_ancestry_6_hierarchyLevel);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_7_id ON fiscal_event_aggregated (departmentEntity_ancestry_7_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_7_code ON fiscal_event_aggregated (departmentEntity_ancestry_7_code);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_7_name ON fiscal_event_aggregated (departmentEntity_ancestry_7_name);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_7_hierarchyLevel ON fiscal_event_aggregated (departmentEntity_ancestry_7_hierarchyLevel);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_8_id ON fiscal_event_aggregated (departmentEntity_ancestry_8_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_8_code ON fiscal_event_aggregated (departmentEntity_ancestry_8_code);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_8_name ON fiscal_event_aggregated (departmentEntity_ancestry_8_name);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_8_hierarchyLevel ON fiscal_event_aggregated (departmentEntity_ancestry_8_hierarchyLevel);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_9_id ON fiscal_event_aggregated (departmentEntity_ancestry_9_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_9_code ON fiscal_event_aggregated (departmentEntity_ancestry_9_code);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_9_name ON fiscal_event_aggregated (departmentEntity_ancestry_9_name);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_9_hierarchyLevel ON fiscal_event_aggregated (departmentEntity_ancestry_9_hierarchyLevel);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_10_id ON fiscal_event_aggregated (departmentEntity_ancestry_10_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_10_code ON fiscal_event_aggregated (departmentEntity_ancestry_10_code);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_10_name ON fiscal_event_aggregated (departmentEntity_ancestry_10_name);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_departmentEntity_ancestry_10_hierarchyLevel ON fiscal_event_aggregated (departmentEntity_ancestry_10_hierarchyLevel);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_expenditure_id ON fiscal_event_aggregated (expenditure_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_expenditure_code ON fiscal_event_aggregated (expenditure_code);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_expenditure_name ON fiscal_event_aggregated (expenditure_name);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_expenditure_type ON fiscal_event_aggregated (expenditure_type);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_project_id ON fiscal_event_aggregated (project_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_project_code ON fiscal_event_aggregated (project_code);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_project_name ON fiscal_event_aggregated (project_name);

CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_coa_id ON fiscal_event_aggregated (coa_id);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_coa_coaCode ON fiscal_event_aggregated (coa_coaCode);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_coa_majorHead ON fiscal_event_aggregated (coa_majorHead);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_coa_majorHeadName ON fiscal_event_aggregated (coa_majorHeadName);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_coa_majorHeadType ON fiscal_event_aggregated (coa_majorHeadType);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_coa_subMajorHead ON fiscal_event_aggregated (coa_subMajorHead);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_coa_subMajorHeadName ON fiscal_event_aggregated (coa_subMajorHeadName);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_coa_minorHead ON fiscal_event_aggregated (coa_minorHead);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_coa_minorHeadName ON fiscal_event_aggregated (coa_minorHeadName);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_coa_subHead ON fiscal_event_aggregated (coa_subHead);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_coa_subHeadName ON fiscal_event_aggregated (coa_subHeadName);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_coa_groupHead ON fiscal_event_aggregated (coa_groupHead);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_coa_groupHeadName ON fiscal_event_aggregated (coa_groupHeadName);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_coa_objectHead ON fiscal_event_aggregated (coa_objectHead);
CREATE INDEX IF NOT EXISTS index_fiscal_event_aggregated_coa_objectHeadName ON fiscal_event_aggregated (coa_objectHeadName);
